Get Single LTK Endpoint
Cox-Automotive/alks-go pull request #26
Opened 2020-06-30 18:21 UTC by amagana3

This PR adds a new endpoint to retrieve a single LTK user from the current account with account information inferred from STS credentials. This is working in both the tests as well as my local test suite.

Also cleaned up another test to remove redundant variable which Go's linter was complaining about. Did not affect the test results, simply cleaned up the code.

2020-07-09 13:35 UTC, webbbarker requested changes
Couple comments, let's discuss.

2020-07-09 13:35 UTC, webbbarker commented on iam_ltk.go
> +	LongTermKey `json:"longTermKey"`
Careful.  This is called `embedding` and actually makes your `GetLongTermKeyResponse` a subclass of both BaseResponse (which is true) and `LongTermKey` which is kinda weird?  You probably want this to be a named field unless your intent is to have users see this response as having the bare long term key fields available AND you reuse the collection of those fields in other places in the codebase as a unit.  What I am trying to get at is that this is not very idiomatic `golang`, so we need to have a good reason for it to be that way or follow the more traditional approach of naming this field (probably also named `LongTermKey`).

2020-07-09 13:35 UTC, webbbarker commented on iam_ltk.go
> +	LongTermKey `json:"longTermKey"`
Reading more of the file, maybe this is OK as is.  Leaving the note so we can discuss.

2020-07-09 13:35 UTC, webbbarker commented on iam_ltk.go
> +	req, err := c.NewRequest(nil, "GET", "/ltk/search/"+iamUsername)
So I didn't get to review you ALKS Core PR, but how is the account name being communicated?  Right now this endpoint looks like it searches every account for a matching LTK.

2020-07-09 15:02 UTC, amagana3 commented
### Update
So I've modified the GET LTK endpoint so it checks for whether we're using STS or non-STS credentials and calls the appropriate endpoint as this endpoint is not _just_ for one or the other.

Also, the `DELETE` and `CREATE` endpoints required no modification because @webbbarker, your previous PR (modifying the login) helped remediate the issue I was having. Now whenever a user calls alks-go their account information is populated when using STS credentials. 👍 

This PR is now up to date and working without issues!

2020-07-10 14:33 UTC, webbbarker requested changes
Let's rearrange the calls a little bit to avoid potential errors.  Otherwise looks good.

2020-07-10 14:33 UTC, webbbarker commented on iam_ltk.go
> +	}
You should only call these two methods if we aren't using STS credentials.  _Technically_ they might not be populated.

2020-07-14 13:44 UTC, webbbarker approved these changes
LGTM.  👍

2020-07-14 13:45 UTC, merged